const mongoose = require('mongoose');

const IMMUTABLE_ERROR_MSG = 'LedgerEntry is append-only and strictly immutable. Updates and deletions are forbidden.';

const ledgerEntrySchema = new mongoose.Schema(
  {
    group: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Group',
      required: [true, 'Ledger entry must belong to a group'],
    },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User is required on ledger entry'],
    },
    counterparty: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    type: {
      type: String,
      enum: ['EXPENSE', 'SETTLEMENT', 'ADJUSTMENT', 'REVERSAL'],
      required: [true, 'Entry type is required'],
    },
    direction: {
      type: String,
      enum: ['CREDIT', 'DEBIT'],
      required: [true, 'Entry direction (CREDIT/DEBIT) is required'],
      description: 'CREDIT = asset/receivable (owed to user); DEBIT = liability/payable (user owes)',
    },
    amount: {
      type: Number,
      required: [true, 'Amount is required'],
      validate: {
        validator: function (val) {
          return Number.isInteger(val) && val > 0;
        },
        message: 'Amount must be a strictly positive integer in cents',
      },
    },
    signedAmount: {
      type: Number,
      validate: {
        validator: Number.isInteger,
        message: 'signedAmount must be an integer',
      },
      description: 'Pre-computed signed value (+ for CREDIT, - for DEBIT) for ultra-fast index-covered aggregations',
    },
    currency: {
      type: String,
      required: [true, 'Currency is required'],
      uppercase: true,
      trim: true,
      minlength: 3,
      maxlength: 3,
      description: 'The group base currency in which amount is stored',
    },
    // Multi-currency audit trail
    originalAmount: {
      type: Number,
      validate: {
        validator: function (val) {
          return val == null || (Number.isInteger(val) && val > 0);
        },
        message: 'originalAmount must be a positive integer in cents',
      },
      description: 'Original amount in originalCurrency before FX conversion',
    },
    originalCurrency: {
      type: String,
      uppercase: true,
      trim: true,
      minlength: 3,
      maxlength: 3,
      description: 'Original expense currency code (e.g. EUR, GBP)',
    },
    exchangeRate: {
      type: Number,
      default: 1.0,
      description: 'FX rate used: originalAmount * exchangeRate = amount (base currency)',
    },
    isFxStale: {
      type: Boolean,
      default: false,
      description: 'True if FX rate was fetched from stale cache due to provider unavailability',
    },
    fxRateTimestamp: {
      type: Date,
      default: null,
      description: 'Timestamp of the FX rate used for conversion',
    },
    expense: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Expense',
      default: null,
    },
    settlementId: {
      type: mongoose.Schema.Types.ObjectId,
      default: null,
    },
    description: {
      type: String,
      trim: true,
      default: '',
    },
    sequence: {
      type: Number,
      default: 1,
    },
  },
  {
    // Append-only: record createdAt, but NEVER updatedAt (documents never change)
    timestamps: { createdAt: true, updatedAt: false },
  }
);

// Pre-validate hook: sync signedAmount and default original currency audit fields
ledgerEntrySchema.pre('validate', function () {
  if (this.amount != null && this.direction) {
    this.signedAmount = this.direction === 'CREDIT' ? this.amount : -this.amount;
  }
  if (this.originalAmount == null && this.amount != null) {
    this.originalAmount = this.amount;
  }
  if (!this.originalCurrency && this.currency) {
    this.originalCurrency = this.currency;
  }
  if (this.exchangeRate == null) {
    this.exchangeRate = 1.0;
  }
});

// =========================================================================
// COMPOUND INDEX STRATEGY
// =========================================================================

// 1. Efficiently query a user's net balance across all their groups in a currency.
//    Covered index: MongoDB can resolve `{ user, currency }` -> `$group by group` -> `$sum signedAmount`
//    entirely in-memory without reading the document from disk!
ledgerEntrySchema.index({ user: 1, currency: 1, group: 1, signedAmount: 1 });

// 2. Chronological audit log of all events in a group
ledgerEntrySchema.index({ group: 1, createdAt: 1 });

// 3. User activity timeline within a specific group
ledgerEntrySchema.index({ group: 1, user: 1, createdAt: 1 });

// 4. Trace all double-entry records generated by a specific settlement batch
ledgerEntrySchema.index({ settlementId: 1 }, { sparse: true });

// =========================================================================
// IMMUTABILITY ENFORCEMENT HOOKS
// =========================================================================

// Document-level hooks: block re-saving existing documents
ledgerEntrySchema.pre('save', function () {
  if (!this.isNew) {
    throw new Error(IMMUTABLE_ERROR_MSG);
  }
});

// Document-level hooks: block document deletion
ledgerEntrySchema.pre('deleteOne', { document: true, query: false }, function () {
  throw new Error(IMMUTABLE_ERROR_MSG);
});

// Query-level hooks: block updates
ledgerEntrySchema.pre(
  ['updateOne', 'updateMany', 'findOneAndUpdate', 'findByIdAndUpdate', 'replaceOne'],
  function () {
    throw new Error(IMMUTABLE_ERROR_MSG);
  }
);

// Query-level hooks: block deletions
ledgerEntrySchema.pre(
  ['deleteOne', 'deleteMany', 'findOneAndDelete', 'findByIdAndDelete'],
  function () {
    throw new Error(IMMUTABLE_ERROR_MSG);
  }
);

const LedgerEntry = mongoose.models.LedgerEntry || mongoose.model('LedgerEntry', ledgerEntrySchema);
module.exports = LedgerEntry;
